# WARNING - Generated by {fusen} from dev/flat_check_data.Rmd: do not edit by hand

test_that("check_plus_in_primary_fur_color works", {
  expect_true(check_plus_in_primary_fur_color("Cinnamon")) 
})
test_that("check_plus_in_primary_fur_color works", {
  expect_false(check_plus_in_primary_fur_color("Cinnamon+Gray")) 
})
