# WARNING - Generated by {fusen} from dev/flat_get_info.Rmd: do not edit by hand

#' Fonction pour avoir le nombre de lignes d'un dataframe
#' 
#' Description
#' Get a message with a number of rows in a data frame.
#'
#' @param df : dataframe to use
#'
#' @importFrom glue glue
#' 
#' @return nrow_df
#' 
#' @export
#' @examples
#' df <- iris
#' get_df_nrows(df)
#' df <- mtcars
#' get_df_nrows(df)
#'
get_df_nrows <- function(df) {
  nrow_df <- nrow(df)
  message(glue("The dataset is composed of {nrow_df} observations"))
  return(nrow_df)
}
